export const TOPICS = [
  'Tell a personal story involving a bee.',
  'Tell a personal story involving bees.',
  'Tell a personal story involving a ladder.',
  'Tell a personal story involving a broken clock.',
  'Tell a personal story involving a shopping cart.',
  'Tell a personal story involving a traffic cone.',
  'Tell a personal story involving a balloon.',
  'Tell a personal story involving a leaking bottle.',
  'Tell a personal story involving a chair.',
  'Tell a personal story involving a spinning fan.',
  'Tell a personal story involving a mirror.',
  'Tell a personal story involving a cracked phone.',
  'Tell a personal story involving a lost shoe.',
  'Tell a personal story involving a backpack.',
  'Tell a personal story involving a key.',
  'Tell a personal story involving a locked door.',
  'Tell a personal story involving a window.',
  'Tell a personal story involving a fence.',
  'Tell a personal story involving a puddle.',
  'Tell a personal story involving a bucket.',
  'Tell a personal story involving a rope.',
  'Tell a personal story involving a coin.',
  'Tell a personal story involving a vending machine.',
  'Tell a personal story involving a receipt.',
  'Tell a personal story involving a pen.',
  'Tell a personal story involving a notebook.',
  'Tell a personal story involving a torn page.',
  'Tell a personal story involving a sticker.',
  'Tell a personal story involving a fridge.',
  'Tell a personal story involving a microwave.',
  'Tell a personal story involving a toaster.',
  'Tell a personal story involving a spoon.',
  'Tell a personal story involving a fork.',
  'Tell a personal story involving a knife.',
  'Tell a personal story involving a plate.',
  'Tell a personal story involving a glass.',
  'Tell a personal story involving a cup.',
  'Tell a personal story involving a sink.',
  'Tell a personal story involving a drain.',
  'Tell a personal story involving a shower.',
  'Tell a personal story involving a towel.',
  'Tell a personal story involving a bar of soap.',
  'Tell a personal story involving a toothbrush.',
  'Tell a personal story involving a sock.',
  'Tell a personal story involving mismatched socks.',
  'Tell a personal story involving a jacket.',
  'Tell a personal story involving a zipper.',
  'Tell a personal story involving a button.',
  'Tell a personal story involving a hat.',
  'Tell a personal story involving sunglasses.',
  'Tell a personal story involving a pair of gloves.',
  'Tell a personal story involving a shoelace.',
  'Tell a personal story involving a staircase.',
  'Tell a personal story involving an elevator.',
  'Tell a personal story involving an escalator.',
  'Tell a personal story involving a hallway.',
  'Tell a personal story involving a ceiling light.',
  'Tell a personal story involving a flickering bulb.',
  'Tell a personal story involving a shadow.',
  'Tell a personal story involving a cardboard box.',
  'Tell a personal story involving a suitcase.',
  'Tell a personal story involving a car door.',
  'Tell a personal story involving a seatbelt.',
  'Tell a personal story involving a steering wheel.',
  'Tell a personal story involving a bicycle.',
  'Tell a personal story involving a flat tire.',
  'Tell a personal story involving a bus stop.',
  'Tell a personal story involving a train ticket.',
  'Tell a personal story involving a map.',
  'Tell a personal story involving a compass.',
  'Tell a personal story involving a street sign.',
  'Tell a personal story involving a bench.',
  'Tell a personal story involving a park gate.',
  'Tell a personal story involving a tree.',
  'Tell a personal story involving a fallen branch.',
  'Tell a personal story involving a rock.',
  'Tell a personal story involving sand.',
  'Tell a personal story involving mud.',
  'Tell a personal story involving a puddle.',
  'Tell a personal story involving a hose.',
  'Tell a personal story involving a sprinkler.',
  'Tell a personal story involving a mailbox.',
  'Tell a personal story involving a letter.',
  'Tell a personal story involving a package.',
  'Tell a personal story involving bubble wrap.',
  'Tell a personal story involving tape.',
  'Tell a personal story involving scissors.',
  'Tell a personal story involving a drawer.',
  'Tell a personal story involving a locked box.',
  'Tell a personal story involving a remote control.',
  'Tell a personal story involving a TV.',
  'Tell a personal story involving static.',
  'Tell a personal story involving a cable.',
  'Tell a personal story involving a charger.',
  'Tell a personal story involving a battery.',
  'Tell a personal story involving a flashlight.',
  'Tell a personal story involving a siren.',
  'Tell a personal story involving a whistle.',
  'Tell a personal story involving a clock tower.',
  'Tell a personal story involving a rubber band.',

  'If you had to make an actually useful invention using a spoon and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a mirror and a rope, what would you make and how would it work?',
  'If you had to make an actually useful invention using a backpack and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a coin and a bottle, what would you make and how would it work?',
  'If you had to make an actually useful invention using a ladder and a phone, what would you make and how would it work?',
  'If you had to make an actually useful invention using a rubber band and a flashlight, what would you make and how would it work?',
  'If you had to make an actually useful invention using a chair and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using a hat and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a key and a notebook, what would you make and how would it work?',
  'If you had to make an actually useful invention using a towel and a fan, what would you make and how would it work?',
  'If you had to make an actually useful invention using a shoe and a magnet, what would you make and how would it work?',
  'If you had to make an actually useful invention using a window and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a drawer and a lock, what would you make and how would it work?',
  'If you had to make an actually useful invention using a glove and a phone, what would you make and how would it work?',
  'If you had to make an actually useful invention using a plate and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using a cup and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a fridge and a timer, what would you make and how would it work?',
  'If you had to make an actually useful invention using a pen and a speaker, what would you make and how would it work?',
  'If you had to make an actually useful invention using a sock and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a zipper and a mirror, what would you make and how would it work?',
  'If you had to make an actually useful invention using a cardboard box and a light, what would you make and how would it work?',
  'If you had to make an actually useful invention using a suitcase and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a car door and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using a seatbelt and a phone, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bicycle and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a flat tire and a pump, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bus stop and a screen, what would you make and how would it work?',
  'If you had to make an actually useful invention using a train ticket and a scanner, what would you make and how would it work?',
  'If you had to make an actually useful invention using a map and a compass, what would you make and how would it work?',
  'If you had to make an actually useful invention using a street sign and a light, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bench and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a tree and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using a branch and a rope, what would you make and how would it work?',
  'If you had to make an actually useful invention using a rock and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using sand and a container, what would you make and how would it work?',
  'If you had to make an actually useful invention using mud and a mold, what would you make and how would it work?',
  'If you had to make an actually useful invention using a puddle and a pump, what would you make and how would it work?',
  'If you had to make an actually useful invention using a hose and a timer, what would you make and how would it work?',
  'If you had to make an actually useful invention using a sprinkler and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a mailbox and a lock, what would you make and how would it work?',
  'If you had to make an actually useful invention using a letter and a scanner, what would you make and how would it work?',
  'If you had to make an actually useful invention using a package and a tracker, what would you make and how would it work?',
  'If you had to make an actually useful invention using bubble wrap and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using tape and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using scissors and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a drawer and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a locked box and a scanner, what would you make and how would it work?',
  'If you had to make an actually useful invention using a remote and a speaker, what would you make and how would it work?',
  'If you had to make an actually useful invention using a TV and a camera, what would you make and how would it work?',
  'If you had to make an actually useful invention using static and a signal booster, what would you make and how would it work?',
  'If you had to make an actually useful invention using a cable and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a charger and a backpack, what would you make and how would it work?',
  'If you had to make an actually useful invention using a battery and a flashlight, what would you make and how would it work?',
  'If you had to make an actually useful invention using a flashlight and a mirror, what would you make and how would it work?',
  'If you had to make an actually useful invention using a siren and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a whistle and a tracker, what would you make and how would it work?',
  'If you had to make an actually useful invention using a clock tower and a light, what would you make and how would it work?',
  'If you had to make an actually useful invention using a rubber band and a motor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a ladder and a camera, what would you make and how would it work?',
  'If you had to make an actually useful invention using a mirror and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bottle and a filter, what would you make and how would it work?',
  'If you had to make an actually useful invention using a cup and a heater, what would you make and how would it work?',
  'If you had to make an actually useful invention using a plate and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a fork and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using a knife and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using a sink and a pump, what would you make and how would it work?',
  'If you had to make an actually useful invention using a drain and a filter, what would you make and how would it work?',
  'If you had to make an actually useful invention using a shower and a timer, what would you make and how would it work?',
  'If you had to make an actually useful invention using a towel and a heater, what would you make and how would it work?',
  'If you had to make an actually useful invention using soap and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a toothbrush and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using socks and a heater, what would you make and how would it work?',
  'If you had to make an actually useful invention using a jacket and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a zipper and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a button and a cable, what would you make and how would it work?',
  'If you had to make an actually useful invention using sunglasses and a camera, what would you make and how would it work?',
  'If you had to make an actually useful invention using gloves and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a shoelace and a tracker, what would you make and how would it work?',
  'If you had to make an actually useful invention using a staircase and a motor, what would you make and how would it work?',
  'If you had to make an actually useful invention using an elevator and a battery, what would you make and how would it work?',
  'If you had to make an actually useful invention using an escalator and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a hallway and a light, what would you make and how would it work?',
  'If you had to make an actually useful invention using a ceiling light and a timer, what would you make and how would it work?',
  'If you had to make an actually useful invention using a flickering bulb and a stabiliser, what would you make and how would it work?',
  'If you had to make an actually useful invention using a shadow and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a cardboard box and a motor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a suitcase and a tracker, what would you make and how would it work?',
  'If you had to make an actually useful invention using a car door and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a seatbelt and a lock, what would you make and how would it work?',
  'If you had to make an actually useful invention using a steering wheel and a screen, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bicycle and a generator, what would you make and how would it work?',
  'If you had to make an actually useful invention using a flat tire and a sealant, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bus stop and a charger, what would you make and how would it work?',
  'If you had to make an actually useful invention using a train ticket and a chip, what would you make and how would it work?',
  'If you had to make an actually useful invention using a map and a screen, what would you make and how would it work?',
  'If you had to make an actually useful invention using a compass and a sensor, what would you make and how would it work?',
  'If you had to make an actually useful invention using a street sign and a camera, what would you make and how would it work?',
  'If you had to make an actually useful invention using a bench and a heater, what would you make and how would it work?',
  'If you had to make an actually useful invention using a tree and a light, what would you make and how would it work?',
  'If you had to make an actually useful invention using a rock and a battery, what would you make and how would it work?'
]

const TEN_MINUTES_MS = 10 * 60 * 1000

export function getTopicWindow(now = Date.now()) {
  return Math.floor(now / TEN_MINUTES_MS)
}

export function getTopicForNow(now = Date.now()) {
  const window = getTopicWindow(now)
  return TOPICS[window % TOPICS.length]
}

export function getTimeLeftMs(now = Date.now()) {
  return TEN_MINUTES_MS - (now % TEN_MINUTES_MS)
}